export { generateVisemeTimeline, getTimelineDurationMs } from './timeline-generator'
export { composeLipSyncVideo, getImageDimensions } from './video-composer'
export type { LipSyncComposeOptions, LipSyncComposeResult } from './video-composer'
export { composeOverlayLipSyncVideo, composeMultiSegmentLipSyncVideo, loadMouthPositionData } from './overlay-composer'
export type { OverlayComposeOptions, OverlayComposeResult, MultiSegmentComposeOptions } from './overlay-composer'
export { MfccProvider, getMfccProvider } from './mfcc-provider'
export type { LipSyncProvider, MfccAnalysisResult, MfccFrame, MouthPosition, MouthPositionData, MouthOverlayConfig } from './types'
