export { generateVisemeTimeline, getTimelineDurationMs } from './timeline-generator'
export { composeLipSyncVideo, getImageDimensions } from './video-composer'
export type { LipSyncComposeOptions, LipSyncComposeResult } from './video-composer'
export { MfccProvider, getMfccProvider } from './mfcc-provider'
export type { LipSyncProvider, MfccAnalysisResult, MfccFrame } from './types'
